# ~/.config/starship.toml

# Use custom format
format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
[â”‚](bold green)$directory$rust$package$node$python$go$java$php$ruby$terraform$docker_context$kubernetes$aws$gcloud$azure
[â””â”€>](bold green) $git_branch$git_status$character"""

# Disable the blank line at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Set 'symbol' to ' ' to turn off symbols
# [package]
# symbol = "ğŸ“¦ "

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bold cyan"

[git_branch]
symbol = "ğŸŒ± "
style = "bold purple"

[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style) )'

[aws]
symbol = "â˜ï¸  "
style = "bold yellow"
format = '[$symbol($profile )(\($region\) )]($style)'

[docker_context]
symbol = "ğŸ³ "
style = "blue"
format = '[$symbol$context]($style) '

[kubernetes]
symbol = "â˜¸ "
style = "cyan"
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

[terraform]
symbol = "ğŸ—  "
style = "bold 105"
format = '[$symbol$workspace]($style) '

[golang]
symbol = "ğŸ¹ "
style = "bold cyan"
format = '[$symbol($version )]($style)'

[python]
symbol = "ğŸ "
style = "yellow"
format = '[$symbol($version )(\($virtualenv\) )]($style)'

[nodejs]
symbol = "ğŸ¢ "
style = "bold green"
format = '[$symbol($version )]($style)'

[java]
symbol = "â˜• "
style = "red"
format = '[$symbol($version )]($style)'
